// Copyright 2016 Esteve Fernandez <esteve@apache.org>
// Copyright 2016-2018 Mickael Gaillard <mick.gaillard@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ros2_rcljava_node_service_NativeService */

#ifndef RCLJAVA__ORG_ROS2_RCLJAVA_NODE_SERVICE_NATIVESERVICE_H_
#define RCLJAVA__ORG_ROS2_RCLJAVA_NODE_SERVICE_NATIVESERVICE_H_

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_ros2_rcljava_node_service_NativeService
 * Method:    nativeCreateServiceHandle
 * Signature: (JLjava/lang/Class;Ljava/lang/String;J;)J
 */
JNIEXPORT jlong JNICALL
  Java_org_ros2_rcljava_node_service_NativeService_nativeCreateServiceHandle
  (JNIEnv *, jclass, jlong, jclass, jstring, jlong);

/*
 * Class:     org_ros2_rcljava_node_service_NativeService
 * Method:    nativeDispose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL
  Java_org_ros2_rcljava_node_service_NativeService_nativeDispose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif  // RCLJAVA__ORG_ROS2_RCLJAVA_NODE_SERVICE_NATIVESERVICE_H_
