// Copyright 2016 Esteve Fernandez <esteve@apache.org>
// Copyright 2016 Mickael Gaillard <mick.gaillard@gmail.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ros2_rcljava_node_topic_Publisher */

#ifndef RCLJAVA__ORG_ROS2_RCLJAVA_NODE_TOPIC_PUBLISHER_H_
#define RCLJAVA__ORG_ROS2_RCLJAVA_NODE_TOPIC_PUBLISHER_H_
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ros2_rcljava_node_topic_Publisher
 * Method:    nativePublish
 * Signature: (JLjava/lang/Object)V
 */
JNIEXPORT void JNICALL Java_org_ros2_rcljava_node_topic_Publisher_nativePublish
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_ros2_rcljava_node_topic_Publisher
 * Method:    nativeDispose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_ros2_rcljava_node_topic_Publisher_nativeDispose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif

#endif  // RCLJAVA__ORG_ROS2_RCLJAVA_NODE_TOPIC_PUBLISHER_H_
