/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_ebinoma_rcljava_Publisher */

#ifndef _Included_io_ebinoma_rcljava_Publisher
#define _Included_io_ebinoma_rcljava_Publisher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_ebinoma_rcljava_Publisher
 * Method:    nativePublish
 * Signature: (JLjava/lang/Object;)
 */
JNIEXPORT void JNICALL Java_io_ebinoma_rcljava_Publisher_nativePublish
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
