/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_ebinoma_rcljava_Node */

#ifndef _Included_io_ebinoma_rcljava_Node
#define _Included_io_ebinoma_rcljava_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_ebinoma_rcljava_Node
 * Method:    createPublisherHandle
 * Signature: (JLjava/lang/Class;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_ebinoma_rcljava_Node_createPublisherHandle
  (JNIEnv *, jclass, jlong, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
