/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_ebinoma_rcljava_RCLJava */

#ifndef _Included_io_ebinoma_rcljava_RCLJava
#define _Included_io_ebinoma_rcljava_RCLJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_ebinoma_rcljava_RCLJava
 * Method:    rcljavaInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_ebinoma_rcljava_RCLJava_rcljavaInit
  (JNIEnv *, jclass);

/*
 * Class:     io_ebinoma_rcljava_RCLJava
 * Method:    createNodeHandle
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_ebinoma_rcljava_RCLJava_createNodeHandle
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_ebinoma_rcljava_RCLJava
 * Method:    getTypesupportIdentifier
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_ebinoma_rcljava_RCLJava_getTypesupportIdentifier
  (JNIEnv *, jclass);

/*
 * Class:     io_ebinoma_rcljava_RCLJava
 * Method:    getRMWIdentifier
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_ebinoma_rcljava_RCLJava_getRMWIdentifier
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
