/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ros2_rcljava_node_Node */

#ifndef _Included_org_ros2_rcljava_node_Node
#define _Included_org_ros2_rcljava_node_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ros2_rcljava_node_Node
 * Method:    nativeCreatePublisherHandle
 * Signature: (JLjava/lang/Class;Ljava/lang/String;Lorg/ros2/rcljava/QoSProfile;)J
 */
JNIEXPORT jlong JNICALL Java_org_ros2_rcljava_node_Node_nativeCreatePublisherHandle
  (JNIEnv *, jclass, jlong, jclass, jstring, jobject);

/*
 * Class:     org_ros2_rcljava_node_Node
 * Method:    nativeCreateSubscriptionHandle
 * Signature: (JLjava/lang/Class;Ljava/lang/String;Lorg/ros2/rcljava/QoSProfile;)J
 */
JNIEXPORT jlong JNICALL Java_org_ros2_rcljava_node_Node_nativeCreateSubscriptionHandle
  (JNIEnv *, jclass, jlong, jclass, jstring, jobject);

/*
 * Class:     org_ros2_rcljava_node_Node
 * Method:    nativeCreateClientHandle
 * Signature: (JLjava/lang/Class;Ljava/lang/String;Lorg/ros2/rcljava/QoSProfile;)J
 */
JNIEXPORT jlong JNICALL Java_org_ros2_rcljava_node_Node_nativeCreateClientHandle
  (JNIEnv *, jclass, jlong, jclass, jstring, jobject);

/*
 * Class:     org_ros2_rcljava_node_Node
 * Method:    nativeCreateServiceHandle
 * Signature: (JLjava/lang/Class;Ljava/lang/String;Lorg/ros2/rcljava/QoSProfile;)J
 */
JNIEXPORT jlong JNICALL Java_org_ros2_rcljava_node_Node_nativeCreateServiceHandle
  (JNIEnv *, jclass, jlong, jclass, jstring, jobject);

/*
 * Class:     org_ros2_rcljava_node_Node
 * Method:    nativeDispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ros2_rcljava_node_Node_nativeDispose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_ros2_rcljava_node_Node
 * Method:    nativeGetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ros2_rcljava_node_Node_nativeGetName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_ros2_rcljava_node_Node
 * Method:    nativeCountPublishers
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ros2_rcljava_node_Node_nativeCountPublishers
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_ros2_rcljava_node_Node
 * Method:    nativeCountSubscribers
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ros2_rcljava_node_Node_nativeCountSubscribers
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_ros2_rcljava_node_Node
 * Method:    getListTopics
 * Signature: (J)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_org_ros2_rcljava_node_Node_getListTopics
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
