/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ros2_rcljava_Node */

#ifndef _Included_org_ros2_rcljava_Node
#define _Included_org_ros2_rcljava_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ros2_rcljava_Node
 * Method:    nativeCreatePublisherHandle
 * Signature: (JLjava/lang/Class;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_ros2_rcljava_Node_nativeCreatePublisherHandle
  (JNIEnv *, jclass, jlong, jclass, jstring);

/*
 * Class:     org_ros2_rcljava_Node
 * Method:    nativeCreateSubscriptionHandle
 * Signature: (JLjava/lang/Class;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_ros2_rcljava_Node_nativeCreateSubscriptionHandle
  (JNIEnv *, jclass, jlong, jclass, jstring);

/*
 * Class:     org_ros2_rcljava_Node
 * Method:    nativeCreateClientHandle
 * Signature: (JLjava/lang/Class;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_ros2_rcljava_Node_nativeCreateClientHandle
  (JNIEnv *, jclass, jlong, jclass, jstring);

/*
 * Class:     org_ros2_rcljava_Node
 * Method:    nativeCreateServiceHandle
 * Signature: (JLjava/lang/Class;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_ros2_rcljava_Node_nativeCreateServiceHandle
  (JNIEnv *, jclass, jlong, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
