/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ros2_rcljava_node_topic_Publisher */

#ifndef _Included_org_ros2_rcljava_node_topic_Publisher
#define _Included_org_ros2_rcljava_node_topic_Publisher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ros2_rcljava_node_topic_Publisher
 * Method:    nativePublish
 * Signature: (JLjava/lang/Object)V
 */
JNIEXPORT void JNICALL Java_org_ros2_rcljava_node_topic_Publisher_nativePublish
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_ros2_rcljava_node_topic_Publisher
 * Method:    nativeDispose
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_ros2_rcljava_node_topic_Publisher_nativeDispose
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
